name: branvier_template
description: A new Branvier project.
version: 0.3.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #Core
  auto_injector: ^2.0.4
  provider: ^6.1.2
  go_router: ^14.0.2
  go_provider: ^1.5.0
  go_transitions: ^0.5.2

  #Http
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  #Services
  hive: ^2.2.3 #Storage
  tr_extension: ^0.5.2 #Translation

  #Ui
  flutter_animate: ^4.5.0
  flutter_async: ^0.8.0
  path_provider: ^2.1.3
  formx: ^0.11.0
  gap: ^3.0.1

  #Utils
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  branvier_lints: ^0.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
  
