// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCK6HS5bazHrLYxtEP9Des-A736tclSM',
    appId: '1:396888538542:web:10a59b70186fb823f71c3f',
    messagingSenderId: '396888538542',
    projectId: 'vanbora-dev-e52f8',
    authDomain: 'vanbora-dev-e52f8.firebaseapp.com',
    storageBucket: 'vanbora-dev-e52f8.appspot.com',
    measurementId: 'G-43P8QW7WXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSCHJDZ0B53hbz58hGjKHcp73zj9Hr8g',
    appId: '1:396888538542:android:0f51d7ad4e22033ff71c3f',
    messagingSenderId: '396888538542',
    projectId: 'vanbora-dev-e52f8',
    storageBucket: 'vanbora-dev-e52f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJHSgtuufkgeSUteL15sH4kaZAYLtnzo',
    appId: '1:396888538542:ios:3af375287a9864faf71c3f',
    messagingSenderId: '396888538542',
    projectId: 'vanbora-dev-e52f8',
    storageBucket: 'vanbora-dev-e52f8.appspot.com',
    iosBundleId: 'com.example.vanbora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMCK6HS5bazHrLYxtEP9Des-A736tclSM',
    appId: '1:396888538542:web:76449e90d936a23bf71c3f',
    messagingSenderId: '396888538542',
    projectId: 'vanbora-dev-e52f8',
    authDomain: 'vanbora-dev-e52f8.firebaseapp.com',
    storageBucket: 'vanbora-dev-e52f8.appspot.com',
    measurementId: 'G-791JB85JP0',
  );

}